### ISSUE TITLE
undefined method `new' for Ark:Module

### ISSUE THREAD

**Issue by khiem-nguyen** [redguide/nodejs#145]
I see that ark 2.0.2 was installed but this error came out. Please help.

```
    ================================================================================
    Error executing action `install` on resource 'ark[nodejs-binary]'
    ================================================================================

    NoMethodError
    -------------
    undefined method `new' for Ark:Module

    Cookbook Trace:
    ---------------
    /home/ec2-user/chef-solo/cookbooks-2/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
    /home/ec2-user/chef-solo/cookbooks-2/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
    /home/ec2-user/chef-solo/cookbooks-2/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
    /home/ec2-user/chef-solo/cookbooks-2/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
    /home/ec2-user/chef-solo/cookbooks-2/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

    Resource Declaration:
    ---------------------
    # In /home/ec2-user/chef-solo/cookbooks-2/nodejs/recipes/nodejs_from_binary.rb

     55: ark archive_name do
     56:   url nodejs_bin_url
     57:   version node['nodejs']['version']
     58:   checksum checksum
     59:   has_binaries binaries
     60:   action :install
     61: end

    Compiled Resource:
    ------------------
    # Declared in /home/ec2-user/chef-solo/cookbooks-2/nodejs/recipes/nodejs_from_binary.rb:55:in `from_file'

    ark("nodejs-binary") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :ark
      cookbook_name :nodejs
      recipe_name "nodejs_from_binary"
      url "https://nodejs.org/dist/v6.2.0/node-v6.2.0-linux-x64.tar.gz"
      version "6.2.0"
      has_binaries ["bin/node", "bin/npm"]
    end

```

**Comment by tas50** [comment]
This usually happens if you're not using a modern Chef client. Try upgrading your client and pulling down the latest ark release. Open this back up if that doesn't resolve it.
