### ISSUE TITLE
npm install bower with '-g' option runs 'npm install -g'

### ISSUE THREAD

**Issue by jslusher** [redguide/nodejs#80]
I'm trying to install the bower package using the -global switch in the resource. I have the following in my recipe:

```ruby
nodejs_npm 'bower' do
  options ['-g']
end
```

I get this when I run the recipe:

```
         * nodejs_npm[bower] action install


             ================================================================================
             Error executing action `run` on resource 'execute[install NPM package bower]'
             ================================================================================

             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             Expected process to exit with [0], but received '1'
             ---- Begin output of npm install  -g  ----
             STDOUT:
             STDERR: npm ERR! addLocal Could not install .
             npm ERR! Error: No version provided
             npm ERR!     at needVersion (/usr/lib/node_modules/npm/lib/cache.js:1244:40)
             npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:1112:10
             npm ERR!     at /usr/lib/node_modules/read-package-json/read-json.js:50:40
             npm ERR!     at final (/usr/lib/node_modules/read-package-json/read-json.js:317:17)
             npm ERR!     at then (/usr/lib/node_modules/read-package-json/read-json.js:124:33)
             npm ERR!     at /usr/lib/node_modules/read-package-json/read-json.js:299:40
             npm ERR!     at fs.js:272:14
             npm ERR!     at /usr/lib/node_modules/graceful-fs/graceful-fs.js:103:5
             npm ERR!     at Object.oncomplete (fs.js:108:15)
             npm ERR! If you need help, you may report this log at:
             npm ERR!     <http://github.com/isaacs/npm/issues>
             npm ERR! or email it to:
             npm ERR!     <npm-@googlegroups.com>

             npm ERR! System Linux 3.10.0-123.4.4.el7.x86_64
             npm ERR! command "node" "/usr/bin/npm" "install" "-g"
             npm ERR! cwd /var/www/discogs
             npm ERR! node -v v0.10.36
             npm ERR! npm -v 1.3.6
             npm ERR!
             npm ERR! Additional logging details can be found in:
             npm ERR!     /var/www/discogs/npm-debug.log
             npm ERR! not ok code 0
             ---- End output of npm install  -g  ----
             Ran npm install  -g  returned 1
```

**Comment by BarthV** [comment]
"Missclic" from my phone.I didn't intend to close this request.
I'll check that

**Comment by mburns** [comment]
You don't need to set the `-g` option to make it global. `nodejs_npm` will make a package global *by default* unless given a path to install to.

```shell
nodejs_npm 'bower'
```

**Comment by BarthV** [comment]
+1
global install option is implicit
